# Generated by Django 3.2 on 2021-04-30 20:43

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('user_tasks', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='TaskChange',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('old_version', models.TextField()),
                ('new_version', models.TextField()),
                ('time_change', models.DateTimeField(auto_now_add=True)),
                ('task', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='changes', to='user_tasks.task')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='task_changes', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
